### ISSUE TITLE
Backend US08: Como usuario deseo agendar el uso de una cancha

### ISSUE THREAD

**Issue by gaha20** [4GeeksAcademy/gaha20-the-last-project#11]

**Comment by gaha20** [comment]
La página de inicio del módulo mostraría una lista de las canchas disponibles. Los usuarios podrían filtrar la lista por tipo de cancha, ubicación y disponibilidad.
Cuando un usuario selecciona una cancha, se le vería una página con más información sobre la cancha, como su tamaño, precio y reglas.
Los usuarios podrían entonces seleccionar la fecha y hora de su reserva. También podrían agregar cualquier

**Comment by aajcs** [comment]
- [ ] canchas disponibles. Los usuarios podrían filtrar la lista por tipo de cancha, ubicación y disponibilidad.

- [ ] Cuando un usuario selecciona una cancha, se le vería una página con más información sobre la cancha, como su tamaño, precio y reglas.

- [ ] Los usuarios podrían entonces seleccionar la fecha y hora de su reserva. También podrían agregar cualquier comentario adicional, como el número de personas que asistirán.

- [ ] Una vez que los usuarios hayan completado el proceso de reserva, se les enviaría un correo electrónico de confirmación.
