### ISSUE TITLE
Frontend US01: Como usuario quiero conocer sobre la plataforma a partir de una Landing page

### ISSUE THREAD

**Issue by bryanstgarcia** [4GeeksAcademy/gaha20-the-last-project#4]
Criterios de aceptación:

- [x]  Logo de la marca

![Image](https://github.com/4GeeksAcademy/gaha20-the-last-project/assets/128089822/f70684cf-bdf0-477b-aa90-c80b0c8f2cc3)

- [ ] Información de contacto y redes de Sports Zone Manager
- [x] Navbar [Logo, Menu, Sign up, Log in]

**Comment by gaha20** [comment]
- [ ] Sumar vista ABOUT US
